name: Generate FlatBuffers code

on:
  pull_request:
      paths:
          - '**.fbs'
env:
    VERSION: v23.3.3
jobs:
  generate_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: Download and extract FlatBuffers compiler
        run: |
          wget https://github.com/google/flatbuffers/releases/download/${{ env.VERSION }}/Linux.flatc.binary.clang++-12.zip
          unzip Linux.flatc.binary.clang++-12.zip
      - name: Generate code
        run: ./flatc --go --gen-object-api schema/fbs/user.fbs
      - name: Check diff
        id: diff
        run: |
          git add -N .
          git diff --exit-code --quiet
        continue-on-error: true
      - name: Commit & Push
        if: steps.diff.outcome == 'failure'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m 'Generate FlatBuffers code'
          git push origin HEAD:${{ github.head_ref }}